2024-08-21 19:18:13,542 ERROR duplicate key value violates unique constraint "coffee_base_category_category_slug_key"
DETAIL:  Key (category_slug)=(bakery) already exists.
 112 
Traceback (most recent call last):
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "coffee_base_category_category_slug_key"
DETAIL:  Key (category_slug)=(bakery) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anishchengre/django/brewing-pathshala/category/api/views/base_category_views.py", line 73, in update
    serializer.save()
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/category/api/serializers/base_category_serializers.py", line 60, in update
    instance.save()
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/base.py", line 1040, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/base.py", line 1105, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: duplicate key value violates unique constraint "coffee_base_category_category_slug_key"
DETAIL:  Key (category_slug)=(bakery) already exists.

2024-08-21 19:18:13,544 ERROR Internal Server Error: /base-categories/bakery-4/ 241 
2024-08-21 19:18:13,544 ERROR "PATCH /base-categories/bakery-4/ HTTP/1.1" 500 61 212 
2024-08-21 19:18:27,249 INFO "GET /admin/category/basecategory/ HTTP/1.1" 200 9580 212 
2024-08-21 19:18:27,320 WARNING Not Found: /favicon.ico 241 
2024-08-21 19:18:28,357 INFO "GET /admin/category/basecategory/139/change/ HTTP/1.1" 200 15140 212 
2024-08-21 19:18:28,401 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-08-21 19:18:28,467 WARNING Not Found: /favicon.ico 241 
2024-08-21 19:18:29,973 INFO "GET /admin/category/basecategory/ HTTP/1.1" 200 9580 212 
2024-08-21 19:18:31,416 INFO "GET /admin/category/basecategory/137/change/ HTTP/1.1" 200 15174 212 
2024-08-21 19:18:31,461 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-08-21 19:18:34,001 INFO "GET /admin/category/basecategory/ HTTP/1.1" 200 9580 212 
2024-08-21 19:18:45,050 INFO /home/anishchengre/django/brewing-pathshala/category/api/serializers/base_category_serializers.py changed, reloading. 266 
2024-08-21 19:18:45,361 INFO Watching for file changes with StatReloader 668 
2024-08-21 19:19:07,780 INFO /home/anishchengre/django/brewing-pathshala/category/api/serializers/base_category_serializers.py changed, reloading. 266 
2024-08-21 19:19:08,237 INFO Watching for file changes with StatReloader 668 
2024-08-21 19:19:09,812 ERROR duplicate key value violates unique constraint "coffee_base_category_category_slug_key"
DETAIL:  Key (category_slug)=(bakery) already exists.
 112 
Traceback (most recent call last):
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "coffee_base_category_category_slug_key"
DETAIL:  Key (category_slug)=(bakery) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anishchengre/django/brewing-pathshala/category/api/views/base_category_views.py", line 73, in update
    serializer.save()
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/category/api/serializers/base_category_serializers.py", line 60, in update
    instance.save()
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/base.py", line 1040, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/base.py", line 1105, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: duplicate key value violates unique constraint "coffee_base_category_category_slug_key"
DETAIL:  Key (category_slug)=(bakery) already exists.

2024-08-21 19:19:09,817 ERROR Internal Server Error: /base-categories/bakery-4/ 241 
2024-08-21 19:19:09,817 ERROR "PATCH /base-categories/bakery-4/ HTTP/1.1" 500 61 212 
2024-08-21 19:19:19,556 INFO "GET /admin/category/basecategory/140/change/ HTTP/1.1" 200 15140 212 
2024-08-21 19:19:19,600 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-08-21 19:19:19,673 WARNING Not Found: /favicon.ico 241 
2024-08-21 19:19:21,558 INFO "GET /admin/category/basecategory/ HTTP/1.1" 200 9580 212 
2024-08-21 19:19:22,992 INFO "GET /admin/category/basecategory/140/change/ HTTP/1.1" 200 15140 212 
2024-08-21 19:19:23,034 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-08-21 19:19:27,950 INFO "GET /admin/category/basecategory/ HTTP/1.1" 200 9580 212 
2024-08-21 19:19:43,956 INFO /home/anishchengre/django/brewing-pathshala/category/api/serializers/base_category_serializers.py changed, reloading. 266 
2024-08-21 19:19:44,266 INFO Watching for file changes with StatReloader 668 
2024-08-21 19:20:09,731 INFO /home/anishchengre/django/brewing-pathshala/category/api/serializers/base_category_serializers.py changed, reloading. 266 
2024-08-21 19:20:10,106 INFO Watching for file changes with StatReloader 668 
2024-08-21 19:20:10,472 INFO "PATCH /base-categories/bakery-4/ HTTP/1.1" 200 68 212 
2024-08-21 19:20:15,530 INFO "GET /admin/category/basecategory/140/change/ HTTP/1.1" 200 15140 212 
2024-08-21 19:20:15,577 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-08-21 19:20:27,978 INFO "PATCH /base-categories/bakery-4/ HTTP/1.1" 200 68 212 
2024-08-21 19:20:30,009 ERROR BaseCategory matching query does not exist. 112 
Traceback (most recent call last):
  File "/home/anishchengre/django/brewing-pathshala/category/api/views/base_category_views.py", line 70, in update
    base_category = BaseCategory.objects.get(category_slug=base_category_slug, is_deleted=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anishchengre/django/brewing-pathshala/coffeeenv/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
category.models.BaseCategory.DoesNotExist: BaseCategory matching query does not exist.
2024-08-21 19:20:30,010 WARNING Bad Request: /base-categories/bakery-4/ 241 
2024-08-21 19:20:30,010 WARNING "PATCH /base-categories/bakery-4/ HTTP/1.1" 400 77 212 
2024-08-21 19:20:31,931 INFO "GET /admin/category/basecategory/140/change/ HTTP/1.1" 200 15173 212 
2024-08-21 19:20:31,964 INFO "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682 212 
2024-08-21 19:20:31,969 INFO "GET /static/admin/js/theme.js HTTP/1.1" 200 1943 212 
2024-08-21 19:20:31,971 INFO "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063 212 
2024-08-21 19:20:31,972 INFO "GET /static/admin/css/base.css HTTP/1.1" 200 21544 212 
2024-08-21 19:20:31,973 INFO "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810 212 
2024-08-21 19:20:31,974 INFO "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347 212 
2024-08-21 19:20:31,974 INFO "GET /static/admin/css/forms.css HTTP/1.1" 200 9090 212 
2024-08-21 19:20:31,975 INFO "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141 212 
2024-08-21 19:20:31,976 INFO "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319 212 
2024-08-21 19:20:31,977 INFO "GET /static/admin/js/core.js HTTP/1.1" 200 6208 212 
2024-08-21 19:20:31,977 INFO "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314 212 
2024-08-21 19:20:31,984 INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3342 212 
2024-08-21 19:20:32,016 INFO "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887 212 
2024-08-21 19:20:32,016 INFO "GET /static/admin/js/actions.js HTTP/1.1" 200 8067 212 
2024-08-21 19:20:32,017 INFO "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042 212 
2024-08-21 19:20:32,019 INFO "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531 212 
2024-08-21 19:20:32,020 INFO "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171 212 
2024-08-21 19:20:32,031 INFO "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905 212 
2024-08-21 19:20:32,032 INFO "GET /static/admin/js/change_form.js HTTP/1.1" 200 606 212 
2024-08-21 19:20:32,060 INFO "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586 212 
2024-08-21 19:20:32,060 INFO "GET /static/admin/css/widgets.css HTTP/1.1" 200 11800 212 
2024-08-21 19:20:32,121 INFO "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331 212 
2024-08-21 19:20:32,130 WARNING Not Found: /favicon.ico 241 
2024-08-21 19:20:32,131 WARNING "GET /favicon.ico HTTP/1.1" 404 4420 212 
2024-08-21 19:20:32,140 INFO "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086 212 
2024-08-21 19:20:32,140 INFO "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677 212 
